config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  devise_for :users
  
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  # VALIDATIONS
  validates :first_name,  presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  validates :bio, presence: true, length: { maximum: 500 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :sanitize_devise_params, if: :devise_controller?

  def sanitize_devise_params
    devise_parameter_sanitizer
      .permit(:sign_up, keys: [:first_name, :last_name, :bio])
  end

  private

  def authenticate_user
    if !user_signed_in?
      redirect_to (new_user_session_path), notice: "Connectez-vous pour accèder à cette page."
      return
    end
    @user = current_user
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
  	@user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
    else
      render 'edit'
    end
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :bio)
  end	
	
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Creative Calling"
    if page_title.empty?
	  return base_title
    else 
	  return page_title + " | " + base_title
    end	
  end	

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
                  <!-- FOOTER -->
                    <footer id="footer" class="footer">
    <div class="footer-top">
        <div class="container">
            <div class="row cols-xs-space cols-sm-space cols-md-space">
                <div class="col-lg-5">
                    <div class="col">
                        <img src="../../assets/images/logo/logo-1-c.png">
                        <span class="clearfix"></span>
                        <span class="heading heading-sm c-gray-light strong-400">One template. Infinite solutions.</span>
                        <p class="mt-3">
                            All the components included in Boomerang are built to the same level of quality as Bootstrap and highlighted with several example pages.
                        </p>

                        <div class="copyright mt-4">
                            <p>
                                Copyright &copy; 2018                                <a href="https://webpixels.io" target="_blank">
                                    <strong>Webpixels</strong>
                                </a> -
                                All rights reserved
                            </p>
                        </div>
                    </div>
                </div>

                <div class="col-lg-2">
                    <div class="col">
                       <h4 class="heading heading-xs strong-600 text-uppercase mb-1">
                           Support
                       </h4>

                       <ul class="footer-links">
                            <li><a href="#" title="Help center">Help center</a></li>
                            <li><a href="#" title="Discussions">Discussions</a></li>
                            <li><a href="#" title="Contact support">Contact</a></li>
                            <li><a href="#" title="Blog">Blog</a></li>
                            <li><a href="#" title="Jobs">FAQ</a></li>
                        </ul>
                     </div>
                </div>

                <div class="col-lg-2">
                    <div class="col">
                        <h4 class="heading heading-xs strong-600 text-uppercase mb-1">
                            Company
                        </h4>

                        <ul class="footer-links">
                             <li>
                                 <a href="#" title="Home">
                                     Home
                                 </a>
                             </li>
                             <li>
                                 <a href="#" title="About us">
                                     About us
                                 </a>
                             </li>
                             <li>
                                 <a href="#" title="Services">
                                     Services
                                 </a>
                             </li>
                             <li>
                                 <a href="#" title="Blog">
                                     Blog
                                 </a>
                             </li>
                             <li>
                                 <a href="#" title="Contact">
                                     Contact
                                 </a>
                             </li>
                         </ul>
                    </div>
                </div>

                <div class="col-lg-3">
                    <div class="col">
                        <h4 class="heading heading-xs strong-600 text-uppercase mb-1">
                            Get in touch
                        </h4>

                        <ul class="social-media social-media--style-1-v4">
                            <li>
                                <a href="#" class="facebook" target="_blank" data-toggle="tooltip" data-original-title="Facebook">
                                    <i class="fa fa-facebook"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="instagram" target="_blank" data-toggle="tooltip" data-original-title="Instagram">
                                    <i class="fa fa-instagram"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="dribbble" target="_blank" data-toggle="tooltip" data-original-title="Dribbble">
                                    <i class="fa fa-dribbble"></i>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="dribbble" target="_blank" data-toggle="tooltip" data-original-title="Github">
                                    <i class="fa fa-github"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

<a href="#" class="back-to-top btn-back-to-top">
    <ion-icon name="arrow-dropup"></ion-icon> 
</a>

app/views/layouts/_home_header.html.erb
<!-- Homepage Navbar-->

	<nav class="navbar navbar-fixed-top navbar-light bg-dark" id="navbar">
  		<div class="container navbar-container">
    		<img id="logo-navbar-image" src="<%= asset_path 'logo_petit.png' %>" class="img-fluid" alt="Responsive image">
    		<h5 class="my-0 mr-md-auto font-weight-normal">
      		<%= link_to "Creative Calling", root_path, class: "border-success font-weight-bold text-black", id: "logo-navbar" %>
    		</h5>
        <% if user_signed_in? %>
    		<nav class="nav navbar-nav navbar-right">
      			<ul class="list-inline" id="navbar-right-buttons">
			        <li id="navbar-right-buttons" class="btn btn-outline-success"><%= link_to "À propos", about_path %></li>
			        <li id="navbar-right-buttons" class="btn btn-outline-success"><%= link_to "Nous contacter", contact_path %></li>
              <li id="navbar-right-buttons" class="btn btn-outline-success"><%= link_to "Mon profil", user_path(current_user) %></li>
              <li id="navbar-right-buttons" class="btn btn-outline-success"><%= link_to "Déconnexion", destroy_user_session_path, method: :delete %></li>
        		</ul>
        </nav>
        <% else %>
        <nav class="nav navbar-nav navbar-right">
            <ul class="list-inline" id="navbar-right-buttons">
              <li id="navbar-right-buttons" class="btn btn-outline-success"><%= link_to "À propos", about_path %></li>
              <li id="navbar-right-buttons" class="btn btn-outline-success"><%= link_to "Nous contacter", contact_path %></li>
              <li id="navbar-right-buttons" class="btn btn-outline-success"><%= link_to "Connexion", new_user_session_path %></li>
              <li id="navbar-right-buttons" class="btn btn-outline-success"><%= link_to "S'enregistrer", new_user_registration_path %></li>
            </ul>
        </nav>
        <% end %>
		</div>
	</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <!-- Favicon -->
    <%= favicon_link_tag asset_path('logo_petit.png'), :rel => 'icon', :type =>  'image/png' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700,800|Roboto:400,500,700" rel="stylesheet"> 

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
  </head>

  <body>
    <%= render 'layouts/home_header' %>

    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "À propos") %>

<div class="container" style="padding-top: 50px;">
	<h2>StaticPages#about</h2>
	<p>Find me in app/views/static_pages/about.html.erb</p>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, "Nous contacter") %>
<div class="container" style="padding-top: 50px;">
	<h2>StaticPages#contact</h2>
	<p>Find me in app/views/static_pages/contact.html.erb</p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Aide") %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/users/show.html.erb
<!-- MAIN WRAPPER -->
<section class="slice-sm sct-color-1">
<div class="profile">
    <div class="container">
        <div class="row cols-xs-space cols-sm-space cols-md-space">
            <div class="col-lg-4">
                <div class="sidebar sidebar--style-2 no-border stickyfill">
                        <div class="widget">
                            <!-- Profile picture -->
                            <div class="profile-picture profile-picture--style-2">
                                <img src="../../assets/images/prv/people/person-7.jpg" class="img-center">
                                <a href="#" class="btn-aux">
                                    <i class="ion ion-edit"></i>
                                </a>
                            </div>

                            <!-- Profile details -->
                            <div class="profile-details">
                                <h2 class="heading heading-4 strong-500 profile-name">Elisabeth Brown</h2>
                                <h3 class="heading heading-6 strong-400 profile-occupation mt-3">Actrice</h3>
                                <h3 class="heading heading-light heading-6 strong-400 profile-location">Paris, France</h3>
                            </div>

                            <!-- Profile connect -->
                            <div class="profile-connect mt-4">
                                <a href="#" class="btn btn-styled btn-block btn-rounded btn-base-1">Follow</a>
                                <a href="#" class="btn btn-styled btn-block btn-rounded btn-base-2">Envoyer message</a>
                            </div>

                            <!-- Profile stats -->
                            <div class="profile-stats clearfix">
                                <div class="stats-entry">
                                    <span class="stats-count">10</span>
                                    <span class="stats-label text-uppercase">Projects</span>
                                </div>
                                <div class="stats-entry">
                                    <span class="stats-count">1.3K</span>
                                    <span class="stats-label text-uppercase">Followers</span>
                                </div>
                            </div>

                            <!-- Profile connected accounts -->
                            <div class="profile-useful-links clearfix">
                                <div class="useful-links">
                                    <a href="#" class="link link--style-1">
                                        <i class="icon ion-social-instagram-outline"></i>
                                        instagram.com/webpixels_io
                                    </a>
                                    <a href="#" class="link link--style-1">
                                        <i class="icon ion-social-dribbble"></i>
                                        dribbble.com/webpixels
                                    </a>

                                    <a href="#" class="link link--style-1">
                                        <i class="icon ion-earth"></i>
                                        webpixels.io
                                    </a>
                                </div>
                            </div>

                            <div class="profile-useful-links clearfix">
                                <div class="useful-links">
                                    <a href="#" class="link link--style-1">
                                        <i class="icon ion-code-download"></i>
                                        Export page as PDF
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>